export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const RESET_BURGER = 'RESET_BURGER'
export const UPDATE_PURCHASEABLE = 'UPDATE_PURCHASEABLE'
